import { AppSettings } from "../types";

export const INITIAL_SETTINGS: AppSettings = {
  binance: {
    connected: false,
    environment: "Demo Only",
    accountType: "Futures",
    apiKey: "Backend-only — not configured in frontend",
    apiSecret: "",
    balance: 0,
    lastSync: "Never",
    permissionStatus: [],
  },
  rules: {
    timeframe1h: "1H (Primary Trend)",
    timeframe15m: "15M (Setup)",
    timeframe5m: "5M (Entry)",
    longEnabled: true,
    shortEnabled: true,
    gradeAPlusEnabled: true,
    gradeAEnabled: true,
    gradeBPlusWatchOnly: true,
    minimumConfidence: 70,
    minimumRiskReward: 2.0,
    allowedStrategies: [
      "Trend Pullback",
      "Breakout Retest",
      "EMA Rejection",
      "Liquidity Sweep Reversal",
      "Continuation Setup",
    ],
    minimum24hVolume: 15000000,
    maximumSignalAgeMinutes: 180,
    sessionStartTime: "00:00",
    sessionEndTime: "23:59",
  },
  risk: {
    riskPerTradePercent: 1.0,
    dailyLossLimitPercent: 3.0,
    dailyProfitLockPercent: 5.0,
    maxOpenTrades: 4,
    maxTotalExposureUsd: 8000,
    maxLeverage: 10,
    perSymbolTradeLimit: 1,
    consecutiveLossPauseCount: 3,
    emergencyStop: false,
    currentRiskStatus: "Blocked",
  },
  automation: {
    autoScan: false,
    autoSignal: false,
    autoExecution: false,
    autoSlTp: false,
    autoMoveToBreakeven: false,
    partialTakeProfit: false,
    scanIntervalSeconds: 14400,
    botStatus: "Paused",
    allowOutsideSession: false,
  },
  notifications: {
    tradeOpened: false,
    tpHit: false,
    slHit: false,
    riskBlock: false,
    connectionLost: true,
    dailyProfitAlert: false,
    dailyLossAlert: false,
    telegramEnabled: false,
    telegramChatId: "",
    browserEnabled: true,
  },
  system: {
    version: "frontend-v1",
    frontendStatus: "Operational",
    backendStatusPlaceholder: "Disconnected until FastAPI responds",
    dataFeedHealthPlaceholder: "Unavailable until backend responds",
    lastEngineUpdatePlaceholder: "Never",
    logRetentionDays: 30,
  },
};
