import { ActiveTrade, AppSettings, JournalTrade, TradeStatus, TradingGrade } from "../types";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function finiteNumber(value: unknown): number | null {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

function nonEmptyString(value: unknown): string | null {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function mergeWithDefaults<T>(candidate: unknown, fallback: T): T {
  if (Array.isArray(fallback)) {
    if (!Array.isArray(candidate)) return fallback;
    if (fallback.every((item) => typeof item === "string")) {
      return candidate.filter((item): item is string => typeof item === "string") as T;
    }
    return candidate as T;
  }
  if (isRecord(fallback)) {
    if (!isRecord(candidate)) return fallback;
    const result: Record<string, unknown> = {};
    for (const [key, defaultValue] of Object.entries(fallback)) {
      result[key] = mergeWithDefaults(candidate[key], defaultValue);
    }
    return result as T;
  }
  return typeof candidate === typeof fallback ? (candidate as T) : fallback;
}

export function loadSettings(key: string, fallback: AppSettings): AppSettings {
  const raw = localStorage.getItem(key);
  if (!raw) return fallback;
  try {
    return mergeWithDefaults(JSON.parse(raw), fallback);
  } catch {
    return fallback;
  }
}

const VALID_GRADES = new Set<TradingGrade>(["A+", "A", "B+", "Rejected", "N/A"]);
const VALID_TRADE_STATUSES = new Set<TradeStatus>([
  "Pending", "Submitted", "Open", "TP1 Hit", "Breakeven Protected", "TP2 Hit", "TP3 Hit",
  "Stop Loss Hit", "Manually Closed", "Risk Engine Closed", "Closed",
]);

function sanitizeTimeline(value: unknown): ActiveTrade["timeline"] {
  if (!Array.isArray(value)) return [];
  return value.flatMap((item) => {
    if (!isRecord(item)) return [];
    const time = nonEmptyString(item.time);
    const event = nonEmptyString(item.event);
    const type = item.type;
    if (!time || !event || (type !== "system" && type !== "action" && type !== "risk")) return [];
    return [{ time, event, type }];
  });
}

function sanitizeActiveTrade(value: unknown): ActiveTrade | null {
  if (!isRecord(value)) return null;
  const id = nonEmptyString(value.id);
  const symbol = nonEmptyString(value.symbol)?.toUpperCase();
  const side = value.side;
  if (!id || !symbol || !/^[A-Z0-9]+$/.test(symbol) || (side !== "Long" && side !== "Short")) return null;

  const requiredNumbers = [
    "score", "entryPrice", "currentPrice", "positionSize", "leverage", "marginUsed",
    "unrealizedPnL", "unrealizedPnLPercent", "stopLoss", "tp1", "tp2", "tp3", "currentRMultiple",
  ] as const;
  const numbers = Object.fromEntries(requiredNumbers.map((field) => [field, finiteNumber(value[field])])) as Record<typeof requiredNumbers[number], number | null>;
  if (requiredNumbers.some((field) => numbers[field] === null)) return null;

  const grade = VALID_GRADES.has(value.grade as TradingGrade) ? (value.grade as TradingGrade) : "N/A";
  const status = VALID_TRADE_STATUSES.has(value.status as TradeStatus) ? (value.status as TradeStatus) : "Pending";
  const locallyTracked = value.source !== "Backend Demo Execution";

  return {
    id,
    symbol,
    side,
    grade,
    score: numbers.score!,
    entryPrice: numbers.entryPrice!,
    currentPrice: numbers.currentPrice!,
    positionSize: numbers.positionSize!,
    leverage: numbers.leverage!,
    marginUsed: numbers.marginUsed!,
    unrealizedPnL: numbers.unrealizedPnL!,
    unrealizedPnLPercent: numbers.unrealizedPnLPercent!,
    stopLoss: numbers.stopLoss!,
    tp1: numbers.tp1!,
    tp2: numbers.tp2!,
    tp3: numbers.tp3!,
    currentRMultiple: numbers.currentRMultiple!,
    duration: nonEmptyString(value.duration) ?? "Unavailable",
    setupName: nonEmptyString(value.setupName) ?? "Unavailable",
    status: locallyTracked ? "Pending" : status,
    openedAt: nonEmptyString(value.openedAt) ?? new Date(0).toISOString(),
    timeline: sanitizeTimeline(value.timeline),
    history: nonEmptyString(value.history) ?? "No validated history available.",
    source: locallyTracked ? "Locally Tracked Demo Plan" : "Backend Demo Execution",
    mode: "Demo",
    executionStatus: locallyTracked ? "Not Submitted / Not Executed" : nonEmptyString(value.executionStatus) ?? "Backend Managed",
    signalStatus: locallyTracked ? "Not Generated by Scanner" : nonEmptyString(value.signalStatus) ?? "Backend Managed",
    exchangeFees: locallyTracked ? "Not Applicable — No Exchange Execution" : nonEmptyString(value.exchangeFees) ?? "Unavailable",
    fundingFees: locallyTracked ? "Not Applicable — No Exchange Execution" : nonEmptyString(value.fundingFees) ?? "Unavailable",
    executionId: locallyTracked ? "No Exchange Execution ID" : nonEmptyString(value.executionId) ?? "Unavailable",
    orderId: locallyTracked ? "No Exchange Order ID" : nonEmptyString(value.orderId) ?? "Unavailable",
  };
}

function sanitizeJournalTrade(value: unknown): JournalTrade | null {
  if (!isRecord(value)) return null;
  const id = nonEmptyString(value.id);
  const date = nonEmptyString(value.date);
  const symbol = nonEmptyString(value.symbol)?.toUpperCase();
  const side = value.side;
  const entry = finiteNumber(value.entry);
  const exit = finiteNumber(value.exit);
  const pnl = finiteNumber(value.pnl);
  const r = finiteNumber(value.r);
  if (!id || !date || !symbol || (side !== "Long" && side !== "Short") || entry === null || exit === null || pnl === null || r === null) return null;
  const grade = VALID_GRADES.has(value.grade as TradingGrade) ? (value.grade as TradingGrade) : "N/A";
  const locallyTracked = value.source !== "Backend Demo Execution";
  return {
    id,
    date,
    symbol,
    side,
    grade,
    strategy: nonEmptyString(value.strategy) ?? "Unavailable",
    entry,
    exit,
    pnl,
    r,
    duration: nonEmptyString(value.duration) ?? "Unavailable",
    exitReason: nonEmptyString(value.exitReason) ?? "Unavailable",
    details: nonEmptyString(value.details) ?? "No validated details available.",
    source: locallyTracked ? "Locally Tracked Demo Plan" : "Backend Demo Execution",
    mode: "Demo",
    executionStatus: locallyTracked ? "Not Submitted / Not Executed" : nonEmptyString(value.executionStatus) ?? "Backend Managed",
    signalStatus: locallyTracked ? "Not Generated by Scanner" : nonEmptyString(value.signalStatus) ?? "Backend Managed",
    exchangeFees: locallyTracked ? "Not Applicable — No Exchange Execution" : nonEmptyString(value.exchangeFees) ?? "Unavailable",
    fundingFees: locallyTracked ? "Not Applicable — No Exchange Execution" : nonEmptyString(value.fundingFees) ?? "Unavailable",
    executionId: locallyTracked ? "No Exchange Execution ID" : nonEmptyString(value.executionId) ?? "Unavailable",
    orderId: locallyTracked ? "No Exchange Order ID" : nonEmptyString(value.orderId) ?? "Unavailable",
  };
}

function parseArray(key: string): unknown[] {
  const raw = localStorage.getItem(key);
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function loadActiveTrades(key: string): ActiveTrade[] {
  return parseArray(key).flatMap((item) => {
    const sanitized = sanitizeActiveTrade(item);
    return sanitized ? [sanitized] : [];
  });
}

export function loadJournalTrades(key: string): JournalTrade[] {
  return parseArray(key).flatMap((item) => {
    const sanitized = sanitizeJournalTrade(item);
    return sanitized ? [sanitized] : [];
  });
}

export function loadFavorites(key: string, fallback: string[]): string[] {
  const values = parseArray(key)
    .filter((item): item is string => typeof item === "string")
    .map((item) => item.trim().toUpperCase())
    .filter((item) => /^[A-Z0-9]+$/.test(item));
  return values.length > 0 ? [...new Set(values)] : fallback;
}
