"""Compatibility exports for the centralized Scanner Contract Version 1 constants."""

from __future__ import annotations

from app.scanner.constants import (
    ACTIVE_REFRESH_INTERVAL,
    AUDIT_CODES,
    CONFIDENCE_QUALIFY_MIN,
    CONFIDENCE_WATCH_MIN,
    CONFIDENCE_WEIGHTS,
    CONTRACT_VERSION,
    ENTRY_NOT_READY_SCORE_CAP,
    FULL_SCAN_INTERVAL,
    FUTURE_CANDLE_TOLERANCE,
    GRADE_A_MIN,
    GRADE_A_PLUS_MIN,
    GRADE_B_PLUS_MIN,
    INVALIDATION_CODES,
    MAX_CLOCK_SKEW,
    MIN_CLOSED_CANDLES,
    QUALIFICATION_EXPIRY,
    REENTRY_COOLDOWN,
    SCANNER_MAX_SYMBOLS,
    SCANNER_RUN_HISTORY_LIMIT,
    SCANNER_TERMINAL_CANDIDATE_LIMIT,
    SCANNER_TERMINAL_HISTORY_LIMIT,
    SCORE_WEIGHTS,
    SETUP_EXPIRY,
    SETUP_MIN_VOLUME_RATIO,
    TIMEFRAME_INTERVAL,
    TIMEFRAME_MAX_AGE,
    UNIVERSE_MAX_AGE,
    VOLATILITY_LIMITS,
    WATCH_REASON_CODES,
)
from app.scanner.constants import (
    SETUP_NAMES as STRING_SETUP_NAMES,
)
from app.schemas.scanner import ScannerSetup

MINIMUM_CANDLES = MIN_CLOSED_CANDLES
FRESHNESS_LIMITS = TIMEFRAME_MAX_AGE
MAX_SELECTED_CANDIDATES = SCANNER_MAX_SYMBOLS
EXPIRY_LIMITS = {ScannerSetup(key): value for key, value in SETUP_EXPIRY.items()}
SETUP_MINIMUM_VOLUME = {
    ScannerSetup(key): value for key, value in SETUP_MIN_VOLUME_RATIO.items()
}
SETUP_NAMES = {ScannerSetup(key): value for key, value in STRING_SETUP_NAMES.items()}
WATCH_CODES = WATCH_REASON_CODES
TERMINAL_CODES = INVALIDATION_CODES

__all__ = [
    "ACTIVE_REFRESH_INTERVAL",
    "AUDIT_CODES",
    "CONFIDENCE_QUALIFY_MIN",
    "CONFIDENCE_WATCH_MIN",
    "CONFIDENCE_WEIGHTS",
    "CONTRACT_VERSION",
    "ENTRY_NOT_READY_SCORE_CAP",
    "EXPIRY_LIMITS",
    "FRESHNESS_LIMITS",
    "FULL_SCAN_INTERVAL",
    "FUTURE_CANDLE_TOLERANCE",
    "GRADE_A_MIN",
    "GRADE_A_PLUS_MIN",
    "GRADE_B_PLUS_MIN",
    "MAX_CLOCK_SKEW",
    "MAX_SELECTED_CANDIDATES",
    "MINIMUM_CANDLES",
    "QUALIFICATION_EXPIRY",
    "REENTRY_COOLDOWN",
    "SCANNER_RUN_HISTORY_LIMIT",
    "SCANNER_TERMINAL_CANDIDATE_LIMIT",
    "SCANNER_TERMINAL_HISTORY_LIMIT",
    "SCORE_WEIGHTS",
    "SETUP_MINIMUM_VOLUME",
    "SETUP_NAMES",
    "TERMINAL_CODES",
    "TIMEFRAME_INTERVAL",
    "UNIVERSE_MAX_AGE",
    "VOLATILITY_LIMITS",
    "WATCH_CODES",
]
